### ISSUE TITLE
Exception while scripting import package not found 

### ISSUE THREAD

**Issue by HaowenWeiJohn** [ApocalyVec/PhysioLabXR#56]
Package not found exception while the import package not found.
All the packages should be python module or imported from the rena root directory (from rena.xxxx.xxxx import xxxx)
Exception:
ModuleNotFoundError: No module named "XXXX"
![image](https://user-images.githubusercontent.com/59973823/218164457-e7731597-15d9-4e01-9dfa-726da104b0b1.png)

**Comment by ApocalyVec** [comment]
@HaowenWeiJohn Has this been resolved by the latest updates to the P300 demo branch?
